version: '3.3'

services:
  web:
    image: flask_img
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=checkinv2
      - POSTGRES_PASSWORD=checkinv2
      - POSTGRES_DB=checkinv2_dev
      
  adminer:
    image: adminer
    restart: always
    depends_on:
      - web
      - db
    ports:
      - 8080:8080
volumes:
  postgres_data: